set(_CATKIN_CURRENT_PACKAGE "common_utilities")
set(common_utilities_VERSION "0.0.0")
set(common_utilities_MAINTAINER "Simon Trendel <simon.trendel@tum.de>")
set(common_utilities_PACKAGE_FORMAT "2")
set(common_utilities_BUILD_DEPENDS "roscpp" "std_msgs" "message_runtime" "roboy_communication_middleware")
set(common_utilities_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "message_runtime" "roboy_communication_middleware")
set(common_utilities_BUILDTOOL_DEPENDS "catkin" "catkin")
set(common_utilities_BUILDTOOL_EXPORT_DEPENDS )
set(common_utilities_EXEC_DEPENDS "roscpp" "std_msgs" "message_runtime" "roboy_communication_middleware")
set(common_utilities_RUN_DEPENDS "roscpp" "std_msgs" "message_runtime" "roboy_communication_middleware")
set(common_utilities_TEST_DEPENDS )
set(common_utilities_DOC_DEPENDS )
set(common_utilities_URL_WEBSITE "")
set(common_utilities_URL_BUGTRACKER "")
set(common_utilities_URL_REPOSITORY "")
set(common_utilities_DEPRECATED "")