using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.1.2_release on 02-Apr-2017 17:15:50
/// Project: powerlink
/// Application process for myoMaster(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 28)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_1;
		[FieldOffset(2)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_2;
		[FieldOffset(4)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_3;
		[FieldOffset(6)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_4;
		[FieldOffset(8)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_5;
		[FieldOffset(10)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_6;
		[FieldOffset(12)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_7;
		[FieldOffset(14)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_8;
		[FieldOffset(16)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_9;
		[FieldOffset(18)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_10;
		[FieldOffset(20)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_11;
		[FieldOffset(22)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_12;
		[FieldOffset(24)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_13;
		[FieldOffset(26)]
		public Int16 CN1_MotorStatus_springDisplacement_I16_14;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 56)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public Int32 CN1_MotorCommand_setPoint_I32_1;
		[FieldOffset(4)]
		public Int32 CN1_MotorCommand_setPoint_I32_2;
		[FieldOffset(8)]
		public Int32 CN1_MotorCommand_setPoint_I32_3;
		[FieldOffset(12)]
		public Int32 CN1_MotorCommand_setPoint_I32_4;
		[FieldOffset(16)]
		public Int32 CN1_MotorCommand_setPoint_I32_5;
		[FieldOffset(20)]
		public Int32 CN1_MotorCommand_setPoint_I32_6;
		[FieldOffset(24)]
		public Int32 CN1_MotorCommand_setPoint_I32_7;
		[FieldOffset(28)]
		public Int32 CN1_MotorCommand_setPoint_I32_8;
		[FieldOffset(32)]
		public Int32 CN1_MotorCommand_setPoint_I32_9;
		[FieldOffset(36)]
		public Int32 CN1_MotorCommand_setPoint_I32_10;
		[FieldOffset(40)]
		public Int32 CN1_MotorCommand_setPoint_I32_11;
		[FieldOffset(44)]
		public Int32 CN1_MotorCommand_setPoint_I32_12;
		[FieldOffset(48)]
		public Int32 CN1_MotorCommand_setPoint_I32_13;
		[FieldOffset(52)]
		public Int32 CN1_MotorCommand_setPoint_I32_14;
	}

}
