/*
* This file was autogenerated by openCONFIGURATOR-2.2.1_release on 09-Feb-2018 17:08:41
* Project: roboy2.0
* Application process for MN(240)
*/
#ifndef XAP_h
#define XAP_h

#define COMPUTED_PI_OUT_SIZE 8
typedef struct
{
	unsigned CN1_ERR_ErrorRegister_U8:8;
	unsigned CN1_NMT_CurrNMTState_U8:8;
	unsigned CN1_DigitalInput_00h_AU8_DigitalInput_1:8;
	unsigned CN1_DigitalInput_00h_AU8_DigitalInput_2:8;
	unsigned CN1_DigitalInput_00h_AU8_DigitalInput_3:8;
	unsigned CN1_DigitalInput_00h_AU8_DigitalInput_4:8;
	unsigned PADDING_VAR_1:16;
} PI_OUT;

#define COMPUTED_PI_IN_SIZE 4
typedef struct
{
	unsigned CN1_DigitalOutput_00h_AU8_DigitalOutput_1:8;
	unsigned CN1_DigitalOutput_00h_AU8_DigitalOutput_2:8;
	unsigned CN1_DigitalOutput_00h_AU8_DigitalOutput_3:8;
	unsigned CN1_DigitalOutput_00h_AU8_DigitalOutput_4:8;
} PI_IN;

#endif
