using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.2.1_release on 12-Feb-2018 18:16:10
/// Project: roboy2.0
/// Application process for MN(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 8)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public byte CN1_DigitalInput_00h_AU8_DigitalInput_1;
		[FieldOffset(1)]
		public byte CN1_DigitalInput_00h_AU8_DigitalInput_2;
		[FieldOffset(2)]
		public byte CN1_DigitalInput_00h_AU8_DigitalInput_3;
		[FieldOffset(3)]
		public byte CN1_DigitalInput_00h_AU8_DigitalInput_4;
		[FieldOffset(4)]
		public byte CN2_DigitalInput_00h_AU8_DigitalInput_1;
		[FieldOffset(5)]
		public byte CN2_DigitalInput_00h_AU8_DigitalInput_2;
		[FieldOffset(6)]
		public byte CN2_DigitalInput_00h_AU8_DigitalInput_3;
		[FieldOffset(7)]
		public byte CN2_DigitalInput_00h_AU8_DigitalInput_4;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 8)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public byte CN1_DigitalOutput_00h_AU8_DigitalOutput_1;
		[FieldOffset(1)]
		public byte CN1_DigitalOutput_00h_AU8_DigitalOutput_2;
		[FieldOffset(2)]
		public byte CN1_DigitalOutput_00h_AU8_DigitalOutput_3;
		[FieldOffset(3)]
		public byte CN1_DigitalOutput_00h_AU8_DigitalOutput_4;
		[FieldOffset(4)]
		public byte CN2_DigitalOutput_00h_AU8_DigitalOutput_1;
		[FieldOffset(5)]
		public byte CN2_DigitalOutput_00h_AU8_DigitalOutput_2;
		[FieldOffset(6)]
		public byte CN2_DigitalOutput_00h_AU8_DigitalOutput_3;
		[FieldOffset(7)]
		public byte CN2_DigitalOutput_00h_AU8_DigitalOutput_4;
	}

}
