using System;
using System.Runtime.InteropServices;

/// <summary>
/// This file was autogenerated by openCONFIGURATOR-2.1.2_release on 27-Mar-2017 16:32:08
/// Project: Demo_3CN
/// Application process for openPOWERLINK_MN(240)
/// </summary>

namespace openPOWERLINK
{

	/// <summary>
	/// Struct : ProcessImage Out
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 4)]
	public struct AppProcessImageOut
	{
		[FieldOffset(0)]
		public byte CN1_DigitalInput_00h_AU8_DigitalInput;
		[FieldOffset(1)]
		public byte PADDING_VAR_1;
		[FieldOffset(2)]
		public byte PADDING_VAR_2;
		[FieldOffset(3)]
		public byte PADDING_VAR_3;
	}

	/// <summary>
	/// Struct : ProcessImage In
	/// </summary>
	[StructLayout(LayoutKind.Explicit, Pack = 1, Size = 4)]
	public struct AppProcessImageIn
	{
		[FieldOffset(0)]
		public byte CN1_DigitalOutput_00h_AU8_DigitalOutput;
		[FieldOffset(1)]
		public byte PADDING_VAR_1;
		[FieldOffset(2)]
		public byte PADDING_VAR_2;
		[FieldOffset(3)]
		public byte PADDING_VAR_3;
	}

}
